### ISSUE TITLE
Instructions needed for generating default data folder from template

### ISSUE THREAD

**Issue by ptrkstr** [b4rtaz/t3mpl-server#2] opened 2022-01-08 09:46 UTC
Hi @b4rtaz,

My process at the moment is duplicating a website from the `t3mpl-templates` repo and then pointing the `t3mpl-server` to it. The problem is that the editor won't load it because the `data` folder is missing (`data.json`, `assets`, `content`).
I'm able to get around this in the meantime by using your [hosted server](https://t3mpl.n4no.com/editor/), opening the same website, exporting the `.t3data` and then pasting the contents to my local data folder.
I'm guessing because your hosted server generates a data folder that there must be a way to do it locally as well.

**Comment by b4rtaz** [comment] 2022-02-03 18:50
Hi @ptrkstr! 

Sorry for the late response.

I think this problem is not directly in t3mpl-server. The server expects a correct configuration by design, so I didn't want to change this.

I've just pushed [this commit](https://github.com/b4rtaz/t3mpl-core/commit/3ec3e2ca1419dd83d780a897604b925b6829768c) into t3mpl-core repo. It adds `--target` parameter to `build` CLI command.

`--target=release` - this works like before, CLI builds a final website,
`--target=data` - this mode generates `data` folder.

If you combine above parameter with `--exampleData=true` flag, you may create `data` folder for any template.

`t3mpl build --manifest=examples\boilerplate-template\template.yaml --exampleData=true --outDir=xyz --target=data`

You should upgrade your t3mpl-core to 0.4.2.

**Comment by ptrkstr** [comment] 2022-02-03 20:46
Hey @b4rtaz

Thanks for getting back to me and coming up with a solution, I really appreciate it! 

I know maintaining a project like this isn't free so I'd love to sponsor your work, would you consider signing up for [github sponsors](https://github.com/sponsors)?

**Comment by b4rtaz** [comment] 2022-02-07 16:49
I've just joined intro [github sponsors](https://github.com/sponsors/b4rtaz).

Can I close this issue?

**Comment by ptrkstr** [comment] 2022-02-07 21:55
Yea please, thank you for joining :)

**Closed as completed** 2022-02-07 21:55 UTC
